sbr/path.c: reworked etcpath() of paths that start with ~.
The initial motivation was to clean up a couple of warnings with
-Wstringop-overflow from gcc 11 with optimization enabled.  For
an input of ~user/file when that user does not exist, the old code
would restore the first '/' after having removed it earlier, to
isolate ~user.  Changed the code to not remove it if that user
doesn't exist.

Added test that exercises that code to test/mhical/test-mhical.

diff --git a/test/mhical/test-mhical b/test/mhical/test-mhical
--- a/test/mhical/test-mhical
+++ b/test/mhical/test-mhical
@@ -1068,6 +1068,20 @@ TZ=GMT mhical <"$MH_TEST_DIR/test1.ics" >"$MH_TEST_DIR/test1.txt"
 check "$expected" "$MH_TEST_DIR/test1.txt"
 rm -f "$MH_TEST_DIR/test1.ics"
 
+# exercise failed getpwnam(3) branch in etcpath()
+start_test 'exercise failed getpwnam(3) branch in etcpath()'
+user='~nmh_user_that_does_not_exist'
+if id $user 2>/dev/null; then
+    echo "$0: user $user exists, cannot run this test"
+    exit 1
+fi
+cat >"$expected" <<EOF
+mhical: unable to open format file $user/mhical.12hour: No such file or directory
+EOF
+printf 'BEGIN:VCALENDAR\nEND:VCALENDAR\n' |
+    uip/mhical -form "$user/mhical.12hour" > "$actual" 2>&1 || true
+check "$expected" "$actual"
+
 
 finish_test
 exit $failed
